### ISSUE TITLE
Update to release 1.8.0 in README.md

### ISSUE THREAD

**Issue by toedter** [Moesif/moesifapi-java#57]
Current readme says:

```
<dependency>
    <groupId>com.moesif.api</groupId>
    <artifactId>moesifapi</artifactId>
    <version>1.7.7</version>
</dependency>

compile 'com.moesif.api:moesifapi:1.7.7'
```

Please update the version to 1.8.0.

I also suggest changing 'compile' to 'implementation' in the gradle example.

See https://www.baeldung.com/gradle-implementation-vs-compile, it says:

NOTE: Starting with Gradle 7.x, the “compile” configuration is no longer used directly. Instead, the “[implementation](https://www.baeldung.com/gradle-dependency-management)” configuration is used for dependencies that are required for both compile and runtime. The “runtimeOnly” configuration is used for dependencies that are only required at runtime.

**Comment by praves77** [comment]
Thanks @toedter . We've updated README to latest moesifapi-java.
